### ISSUE TITLE
Release .tar.gz as a GitHub artifact to keep a stable hash

### ISSUE THREAD

**Issue by grencez** [gpakosz/peg#4]
The `sha256sum` of https://github.com/gpakosz/peg/archive/refs/tags/0.1.18.tar.gz used to be aa25b2e10cc673a0a6f20114b0dc5cfc6ce221d1c257852fe4128f0782cbb585 but is now                          d5031a3cce592ea6d002a4996be8165775fdabf4f393857dfe1601f02078a8ae. I suspect this is due to https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/ like what happened last year. It's more-or-less expected now whenever GitHub's packaging algorithm changes slightly.

Would it be too much trouble to upload an "artifact" cutting a release? Even better if it's the exact .tar.gz from Ian's website.

An artifact for v0.1.18 would be helpful for me in particular. I could always make a fork or point my code to Ian's website, but a stable .tar.gz package seems appropriate here too.

**Comment by gpakosz** [comment]
Hello. I believe it's because I rewrote the history of the repository and some line ending changes because of global `.gitattributes` I have 😢

I never expected people to reference releases here tbh. Not sure how to move forward.

**Comment by grencez** [comment]
Well if your goal is essentially a mirror, just uploading a `.tar.gz` alongside a release's autogenerated package should be enough. Oh... you don't have releases (https://github.com/gpakosz/peg/releases), only tags.

I think this repository would be more useful if it had and releases... and of course if its history didn't change anymore. But if you want to run it differently, I can respect that.

**Comment by gpakosz** [comment]
I will pay attention to not altering the history again.

I went ahead and added "proper" releases, and I uploaded the `.zip` and `.tar.gz` files I just downloaded from the tags: https://github.com/gpakosz/peg/releases

**Comment by grencez** [comment]
Yep, that's all it takes!

It's probably fine to omit the `.zip`. I see plenty of projects that only have the `.tar.gz` like https://github.com/bazelbuild/rules_proto/releases/tag/6.0.0-rc2. The only reason to do this is for reproducible hashes for build tools (Bazel & CMake in my case), so there's not much point in providing more than 1 option. But there's no harm in it, if you prefer both.

**Comment by gpakosz** [comment]
Well it's so lightweight that I believe we can keep both

**Comment by grencez** [comment]
My code's building again after [updating the URL and hash](https://github.com/ProtocolConvergence/protocon/commit/e364db20c1278eeec6cd3be17ec9a1764c90a274) as expected. And now it won't break when GitHub updates their compression settings.

Thanks a bunch!

**Comment by gpakosz** [comment]
No problem
